version: "3"

services:

  # Container: UnManic
  unmanic:
    image: josh5/unmanic:latest
    container_name: UnManic
    environment:
      - TZ=America/New_York # Time Zone
      - PUID=1026           # User ID
      - PGID=100            # Group ID
    volumes:
      # NAS folder | Container folder
      - /volume1/docker/Containers/UnManic/config:/config
      - /volume1/HTPC:/library
      - /volume1/docker/Containers/UnManic/transcode:/tmp/unmanic
    ports:
      # NAS | Container
      - 8888:8888/tcp
    deploy:
      resources:
        limits:
          memory: 1G
    restart: unless-stopped