version: "3.3"
services:
  decluttarr:
    image: ghcr.io/manimatter/decluttarr:latest
    # Container: Decluttarr
    container_name: Decluttarr
    restart: always
    environment:
      TZ: America/New_York
      PUID: 1026
      PGID: 100

      ## General
      # TEST_RUN: True
      # SSL_VERIFICATION: False
      LOG_LEVEL: INFO

      ## Features 
      REMOVE_TIMER: 10
      REMOVE_FAILED: True
      REMOVE_FAILED_IMPORTS: True
      REMOVE_METADATA_MISSING: True
      REMOVE_MISSING_FILES: True
      REMOVE_ORPHANS: True
      REMOVE_SLOW: True
      REMOVE_STALLED: True
      REMOVE_UNMONITORED: True
      RUN_PERIODIC_RESCANS: '
        {
          "SONARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7},
          "RADARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7}
        }'

     # Feature Settings
      PERMITTED_ATTEMPTS: 3
      NO_STALLED_REMOVAL_QBIT_TAG: Don't Kill
      MIN_DOWNLOAD_SPEED: 100     
      FAILED_IMPORT_MESSAGE_PATTERNS: '
        [
          "Not a Custom Format upgrade for existing", 
          "Not an upgrade for existing"
        ]'

      ## Radarr
      RADARR_URL: http://<NAS IP>:8083
      RADARR_KEY: <API KEY>

      ## Sonarr
      SONARR_URL: http://<NAS IP>:8082
      SONARR_KEY: <API KEY>

      ## Lidarr
      LIDARR_URL: http://<NAS IP>:8084
      LIDARR_KEY: <API KEY>

      ## Readarr
      READARR_URL: http://<NAS IP>:8086
      READARR_KEY: <API KEY>

      ## Whisparr
      #WHISPARR_URL: http://<NAS IP>:8089
      #WHISPARR_KEY: <API KEY>

      ## qBitorrent
      QBITTORRENT_URL: http://<NAS IP>:8080
      QBITTORRENT_USERNAME: <username>
      QBITTORRENT_PASSWORD: <password>