services:
  # Container: VaultWarden
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: VaultWarden
    restart: always
    environment:
      # required when using a reverse proxy; your domain; vaultwarden needs to know it's https to work properly with attachments
      # DOMAIN: "https://vaultwarden.example.com"
      # Deactivate this with "false" after you have created your account so that no strangers can register
      SIGNUPS_ALLOWED: "false"
    volumes:
      # NAS / Container
      - /volume1/docker/Containers/VaultWarden:/data
    ports:
      # NAS | Container
      - 8070:80