services:

  # Container #1 - Bazarr-sync
  bazarr-sync:
    image: ghcr.io/ajmandourah/bazarr-sync:latest
    container_name: Bazarr-sync
    volumes:
      # NAS | Container
      # Config file
      - /volume1/docker/Containers/Bazarr-sync/config.yaml:/usr/src/app/config.yaml
    command: ["bazarr-sync", "sync", "movies", "shows"]
    # deploy:
    #  resources:
    #    limits:
    #      # Hard limit
    #      memory: 768M
    #    reservations:
    #      # Minimum guaranteed memory
    #      memory: 128M
    restart: no