# Create the Nextcloud Namespace (if not exist)
# Create Kubernetes Secrets for the NextCloud applications.
# It contains sensitive information such as database credentials and admin user credentials.
# NOTE: Make sure to replace the placeholders with actual values before applying this configuration.

apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
  namespace: nextcloud
type: Opaque
stringData:
  POSTGRES_DB: nextcloud
  POSTGRES_USER: nextcloud
  POSTGRES_PASSWORD: password
  NEXTCLOUD_ADMIN_USER: admin
  NEXTCLOUD_ADMIN_PASSWORD: password