version: "3"

services:

  # Container #1: Pi-Hole - This container is the ad blocker.
  # -------------------------
  pihole:
    image: pihole/pihole:latest
    container_name: Pi-Hole
    # The container now needs more capabilities to run properly
    cap_add:
      - CAP_CHOWN
      - CAP_NET_ADMIN
      - CAP_NET_BIND_SERVICE
      - CAP_NET_RAW
      - CAP_SYS_NICE
      - CAP_SYS_TIME
      - NET_ADMIN
    ports:
      # NAS | Container
      - 53:53/tcp           # DNS Service
      - 53:53/udp           # DNS Service
      #- 8079:80             # HTTP UI - Check if your container is using 80 or 8080 and uncomment the right one if you are going to use plain HTTP
      #- 8079:8080           # HTTP UI
      - 8079:443            # HTTPS UI - Check if your container is using 443 or 8443 and uncomment the right one if you are going to use HTTPS
      #- 8079:8443           # HTTPS UI
      #- 67:67               # DHCP - Only if you plan to use Pi-Hole as a DHCP server
    environment:
      - TZ=America/New_York # Time Zone
      - PUID=1026           # User ID
      - PGID=100            # Group ID
      - FTLCONF_webserver_api_password=password # Web Interface password
      - FTLCONF_dns_listeningMode=all # Make sure to listen to all DNS requests
    volumes:
      # NAS folder | Container folder
      - /volume1/docker/Containers/PiHole/dnsmasq.d:/etc/dnsmasq.d
      - /volume1/docker/Containers/PiHole/pihole:/etc/pihole
    deploy:
      resources:
        limits:
          memory: 1G        # Limit the memory usage to 1GB
    restart: unless-stopped