version: "3"

services:
  # Container: Whisparr
  whisparr:
    image: hotio/whisparr:latest
    container_name: Whisparr
    environment:
      - TZ=America/New_York # Time Zone
      - PUID=1026           # User ID
      - PGID=100            # Group ID
    volumes:
      # NAS folder | Container folder
      - /volume1/docker/Containers/Whisparr:/config
      - /volume1/HTPC:/HTPC
    ports:
      # NAS | Container
      - 8092:6969/tcp
    deploy:
      resources:
        limits:
          memory: 1G
    restart: unless-stopped