services:
  # Actual Budget application
  actual_server:
    image: actualbudget/actual-server:latest
    ports:
      # NAS | Container
      - '5006:5006'
    environment:
      TZ: America/New_York
      PUID: 1026
      PGID: 100
      # Uncomment any of the lines below to set configuration options.
      ACTUAL_HTTPS_KEY: /data/ab.key
      ACTUAL_HTTPS_CERT: /data/ab.crt
      # - ACTUAL_PORT=5006
      # - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      # - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      # - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
    volumes:
      # NAS | Container
      - /volume1/docker/Containers/Actual Budget:/data
    restart: unless-stopped