{{- range $name, $_ := $.Values.storageClasses }}
{{- if not .disabled }}
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ default "false" .isDefault | quote }}
  labels: {{- include "synology-csi.labels" $ | nindent 4 }}
  name: {{ $name }}
{{- with .parameters }}
parameters: {{- toYaml . | nindent 2 }}
{{- end }}
provisioner: csi.san.synology.com
{{- with .reclaimPolicy }}
reclaimPolicy: {{ . }}
{{- end }}
{{- with .volumeBindingMode }}
volumeBindingMode: {{ . }}
{{- end }}
{{- end }}
{{- end }}
